"""highest_bid_auction

Revision ID: 48c9cd00e4bf
Revises: 5a8ec7e44930
Create Date: 2026-09-25 07:11:15.293323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c9cd00e4bf'
down_revision: Union[str, Sequence[str], None] = '5a8ec7e44930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('highest_bid', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'highest_bid')
    # ### end Alembic commands ###
