"""bid_remove_ts_seq

Revision ID: 5a8ec7e44930
Revises: 98f7aa11e6bd
Create Date: 2026-09-23 11:46:09.344019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8ec7e44930'
down_revision: Union[str, Sequence[str], None] = '98f7aa11e6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ux_bid_ts_seq'), 'bids', type_='unique')
    op.drop_column('bids', 'bid_ts')
    op.drop_column('bids', 'bid_seq')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('bid_seq', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('bids', sa.Column('bid_ts', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('ux_bid_ts_seq'), 'bids', ['bid_ts', 'bid_seq'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
