"""remove_auction_winner

Revision ID: 8252e27ef97c
Revises: b4b1714bf9db
Create Date: 2026-09-25 09:44:14.872995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8252e27ef97c'
down_revision: Union[str, Sequence[str], None] = 'b4b1714bf9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auction_winners')
    op.alter_column('bids', 'bid_seq',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=None, start=1, increment=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bids', 'bid_seq',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False)
    op.create_table('auction_winners',
    sa.Column('auction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bid_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], name=op.f('auction_winners_auction_id_fkey')),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], name=op.f('auction_winners_bid_id_fkey')),
    sa.PrimaryKeyConstraint('auction_id', 'bid_id', name=op.f('auction_winners_pkey'))
    )
    # ### end Alembic commands ###
