"""booking_seat_update

Revision ID: 908094571bae
Revises: 03777557ecaf
Create Date: 2026-08-14 16:51:44.270284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '908094571bae'
down_revision: Union[str, Sequence[str], None] = '03777557ecaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('uc_seat_id_status', 'bookings', ['status', 'seat_id'], unique=True, postgresql_where=sa.text("status = 'pending' OR status = 'confirmed'"))
    op.add_column('seats', sa.Column('is_booked', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('seats', sa.Column('is_held', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seats', 'is_held')
    op.drop_column('seats', 'is_booked')
    op.drop_index('uc_seat_id_status', table_name='bookings', postgresql_where=sa.text("status = 'pending' OR status = 'confirmed'"))
    op.drop_column('bookings', 'canceled_at')
    op.drop_column('bookings', 'confirmed_at')
    # ### end Alembic commands ###
