"""add_seq_to_bids

Revision ID: b4b1714bf9db
Revises: 48c9cd00e4bf
Create Date: 2026-09-25 09:29:22.271810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4b1714bf9db"
down_revision: Union[str, Sequence[str], None] = "48c9cd00e4bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bids", sa.Column("bid_seq", sa.Integer(), sa.Identity(always=None, start=1, increment=1), nullable=False)
    )
    op.create_unique_constraint(None, "bids", ["bid_seq"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bids", type_="unique")
    op.drop_column("bids", "bid_seq")
    # ### end Alembic commands ###
