"""bid_ts_seq

Revision ID: c1a55d820ceb
Revises: 3ba6235fea06
Create Date: 2026-09-12 07:29:13.576805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a55d820ceb'
down_revision: Union[str, Sequence[str], None] = '3ba6235fea06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('bid_ts', sa.BigInteger(), nullable=False))
    op.execute(
        sa.text("ALTER TABLE bids ALTER COLUMN bid_seq TYPE BIGINT USING bid_seq::BIGINT")
    )
    op.drop_constraint(op.f('bids_bid_seq_key'), 'bids', type_='unique')
    op.create_unique_constraint('ux_bid_ts_seq', 'bids', ['bid_ts', 'bid_seq'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux_bid_ts_seq', 'bids', type_='unique')
    op.create_unique_constraint(op.f('bids_bid_seq_key'), 'bids', ['bid_seq'], postgresql_nulls_not_distinct=False)
    op.alter_column('bids', 'bid_seq',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('bids', 'bid_ts')
    # ### end Alembic commands ###
