"""auction_owner_id

Revision ID: cc01bf3ad1f5
Revises: 8133c91571f7
Create Date: 2026-08-22 12:52:20.168617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc01bf3ad1f5'
down_revision: Union[str, Sequence[str], None] = '8133c91571f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('auction_owner_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('auctions_user_id_fkey'), 'auctions', type_='foreignkey')
    op.create_foreign_key(None, 'auctions', 'users', ['auction_owner_id'], ['id'], ondelete='SET NULL')
    op.drop_column('auctions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'auctions', type_='foreignkey')
    op.create_foreign_key(op.f('auctions_user_id_fkey'), 'auctions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('auctions', 'auction_owner_id')
    # ### end Alembic commands ###
